### PR TITLE
test(Breakpoint): Add basic coverage

### PR DESCRIPTION
**Pull request by lukelooker**
Simple coverage for `Breakpoint` component

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [x] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

### CODE REVIEW

**Review by dbchristopher — DISMISSED** [review]
Very nice! When I coded the Breakpoint component I set the [global jest viewport](https://github.com/looker-open-source/components/blob/main/jest.setup.js#L50-L58) to be 800x600. Since these tests rely on that specific setting, do you think it's worth hard-coding that into a `beforeEach` block here? Just to make sure some other test doesn't change it and break things.

**Comment by ElliotTheHuman** [comment]
> Very nice! When I coded the Breakpoint component I set the [global jest viewport](https://github.com/looker-open-source/components/blob/main/jest.setup.js#L50-L58) to be 800x600. Since these tests rely on that specific setting, do you think it's worth hard-coding that into a `beforeEach` block here? Just to make sure some other test doesn't change it and break things.

I think this would help confused folks like me who didn't know that the global jest viewport width was set to 800px in the config file 😆 

Alternatively, having a comment that points to the `jest.setup` file could be helpful. Feel free to disregard this if this is mostly common sense for others though.

**Comment by dbchristopher** [comment]
@ElliotTheHuman lol a comment at least is a great idea! Anything that's dependent on jest config is never very intuitive

**Comment by lukelooker** [comment]
@ElliotTheHuman / @dbchristopher - Great point on the viewport issue. Added a note to the test. TY!

**Review by ElliotTheHuman — APPROVED** [review]
Thanks for adding the note in the test suite. LGTM!

**Pull request merged**
