### PR TITLE
chore(deps): Loosen package.json resolutions

### PR DESCRIPTION
**Pull request by lukelooker**
Generally we use package.json resolutions to REQUIRE a newer version of a transient dependency to prevent the usage of transient dependencies with known vulnerabilities.

This PR loostens that requirement to require the fixed version or NEWER instead of explicitly locking to the fix version specifically

### CODE REVIEW

**Comment by lukelooker** [comment]
@mdodgelooker - If you have a chance can you give this a look? Hoping to land this so I can get a few more dependency upgrade PRs rolling (I suspect `yarn.lock` changes will conflict so trying to keep number of concurrents low :)

**Comment by mdodgelooker** [comment]
👀

**Review by mdodgelooker — APPROVED** [review]
LGTM

Each of those resolutions were due to an issue with older version of the package, right – never with a newer version?

**Comment by lukelooker** [comment]
> Each of those resolutions were due to an issue with older version of the package, right – never with a newer version?

Yep, all are cases where a transient dependency had/has a vulnerability so we wanted to make sure that the package is always installed with the fix version [or better]. Before the specificity meant that even if the dependency specified a newer version our explicitly specified version would win.

**Pull request merged**
