### PR TITLE
feat: Consistent border on ButtonToggle, ButtonGroup, Chip, ChipButton, & InputFilters

### PR DESCRIPTION
**Pull request by mdodgelooker**
- Replaces `ui2` with `ui3` on borders in buttons and chips as well as `InputFilters`
- The `ButtonGroup` & `ButtonToggle` focus style looked not great so I updated it to look more like input focus
  - Then I checked Material examples and for button focus it's all about the ripple. I did try adding the ripple just for fun but it looks off with ripple opacity over a selected button's background.
  - Thoughts? Should I just leave the old focus style?
  - Old: 8b979b13-e455-41d6-9493-e4652af9b591
  - New: e954495f-d128-4ac6-862a-52b9d4b4144f

### CODE REVIEW

**Review by lukelooker — COMMENTED** [review]
I like the consistency this brings but I'd defer to @jhardy as to whether it's the right design / Material decision.

**Comment by jhardy** [comment]
Overall I like the consistency. I do think the focus style on mouse interactions is now a bit heavy, is there a way to leverage `focus-visible` functionality for `ButtonToggle` and `ButtonGroup`? I think some areas of core product will be a bit averse to to a drastic change is focus style here. 

Ideally scenario is ripple for mouse interactions and box-shadow focus style for keyboard.

**Comment by mdodgelooker** [comment]
@jhardy will do! And just to confirm, by box-shadow for keyboard, you mean the new version that basically just looks like a 2px border? 🙂

**Comment by jhardy** [comment]
@mdodgelooker yup, thats the one.

**Comment by mdodgelooker** [comment]
@jhardy I restricted the heavy border to keyboard "focus visible". Is it ok for this to go in before the ripple?

**Review by lukelooker — APPROVED** [review]
Code LGTM - leaving design feedback to Jared.

**Comment by jhardy** [comment]
Ripple can wait. This looks good to me.

**Review by jhardy — APPROVED** [review]

**Pull request merged**
