### PR TITLE
Fixed rel not being passed down to internal link element bug

### PR DESCRIPTION
**Pull request by ElliotTheHuman**
### :sparkles: Changes

- Explicitly passed "rel" prop to "link" element of `MenuItemInternal`
- Added new "Link" story to `MenuItem` stories (includes snapshot)

### :white_check_mark: Requirements

- [x] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### CODE REVIEW

**Review by lukelooker — CHANGES_REQUESTED** [review]
Can you include a jest test that proves the no-opener happens for link MenuItems? :)

**Review by lukelooker — APPROVED** [review]
LGTM!

**Comment by whscullin** [comment]
FWIW the Link component also automatically appends `"noopener noreferrer"` to `rel` if `target="_blank"` (even if you've already done it because this feature is not documented). It might be nice to make MenuItem behave the same.

**Comment by ElliotTheHuman** [comment]
Good catch. I should've included the behavior on this PR. ^ 

I'm writing up a follow-up PR that gets link `MenuItem`s to be consistent with how `Link` auto-appends `"noopener noreferrer"`.

**Comment by ElliotTheHuman** [comment]
Follow-up PR to get the auto append behavior in to `MenuItem`:
https://github.com/looker-open-source/components/pull/1576

**Pull request merged**
