### PR TITLE
chore(Playground): Correct dependency versions to get `yarn playground` working again

### PR DESCRIPTION
**Pull request by lukelooker**
How to test:

```
yarn checkout luke/playground-fix
yarn
yarn playground
```

### CODE REVIEW

**Review by swhitey — DISMISSED** [review]
it works!

**Comment by lukelooker** [comment]
@swhitey My original version fixed playground but broke Storybook along the way. This narrower version fixes without breaking others.

**Review by mdodgelooker — APPROVED** [review]
👍 
Successfully ran playground, storybook, & gatsby. Thanks for fixing @lukelooker!

**Comment by mdodgelooker** [comment]
...playground isn't working in IE11 but that can be a fix for another day.

**Pull request merged**
