### PR TITLE
fix(DataTable): Safari stick cell bug

### PR DESCRIPTION
**Pull request by laraharrow**
in Safari the DataTable sticky cell wasn't behaving properly.
Screen Shot 2021-02-24 at 5 20 54 PM

to see the error on PDT open the link below in Safari:

To repeat the error:
1. on `columns.ts` line 33
    - switch `size: 'medium',` for `size: 'nowrap',`
2. on `item.tsx` line 78
    - remove ` description={type}`
3. open storybook on `datatable--select-active-items`  in Safari and make the screen smaller so the first column is sticky. The `border-bottom` on that first column changes place.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [x] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [x] not applicable

### CODE REVIEW

**Comment by laraharrow** [comment]
Here is the fix:

https://user-images.githubusercontent.com/23616264/109089263-cb841d00-76c5-11eb-96c4-02e66288a549.mov

**Comment by lukelooker** [comment]
Just rebased this branch to clean-out unrelated commits. :)

**Comment by lukelooker** [comment]
Interestingly the image-snapshots is pointing out a change in the DataTable/Percentage snaphshot:

image

@laraharrow Can you investigate why this changed?

**Review by lukelooker — APPROVED** [review]
Works great in Safari and I don't see any regressions in Chrome or Firefox. Ship it! :)

**Pull request merged**
