### PR TITLE
fix(MenuHeading): Fix MenuHeading style overrides

### PR DESCRIPTION
**Pull request by ElliotTheHuman**
Added `className` to `MenuHeading` props to allow for style overrides. We need style overrides specifically as a part of the HT `Menu` refactor work, where we're swapping `MenuHeading`s in for existing `MenuGroup`s which can specific label styling. 

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

### CODE REVIEW

**Review by dbchristopher — CHANGES_REQUESTED** [review]
The code looks fine, but is there any way we can avoid doing this? We've said in the past that once HT developers start overriding css it takes us down a dark path. How about if we update the MenuHeading to accept `TypographyProps` and pass those down directly?

**Comment by dbchristopher** [comment]
@ElliotTheHuman I opened up a PR into this branch to show what I mean. I think we should try to keep people on rails as much as possible and prevent them from introducing arbitrary style overrides. Otherwise it can make future upgrades a lot more brittle and painful! https://github.com/looker-open-source/components/pull/2004

**Comment by ElliotTheHuman** [comment]
Hey Daniel. Merged in your props-oriented suggestion; it definitely makes sense to maintain customization control / keep people on the happy path via props.

Also added in "ColorProps" after doing a brief look over what other style overrides are happening in HT.

**Review by dbchristopher — APPROVED** [review]
Ok cool! Looks great 👍

**Pull request merged**
