### PR TITLE
UnorderedList and OrderedList

### PR DESCRIPTION
**Pull request by ElliotTheHuman**
### :sparkles: Changes

- Added `UnorderedList` and `OrderedList` components
  - Will replace the existing `List` component so that the "List" name can go to future `List` component
- **TODO:** 
  - Remove `List` and `ListItem` from codebase, and replace existing usages with `OrderedList` and `UnorderedList`
~~- Add docs in a future PR to keep line count low (but can include those in this PR if requested)~~ <--  Included as a part of this PR

### :white_check_mark: Requirements

- [x] Includes test coverage for all changes
- [ ] Build and tests are passing
- [x] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [x] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [x] PR is ideally < ~400LOC

### :camera: Screenshots
UnorderedList (type = "none"):
Screen Shot 2021-01-06 at 12 49 07 PM

OrderedList (type = "number"):
Screen Shot 2021-01-06 at 12 48 59 PM

### CODE REVIEW

**Review by lukelooker — COMMENTED** [review]
LGTM

When adding documentation for OrderedList & UnorderedList let's file those under "Text" in the site navigation :)

**Review by lukelooker — APPROVED** [review]

**Review by lukelooker — CHANGES_REQUESTED** [review]
Sorry, lost my own notes, changes look good but I think it'd be worthwhile to include the Storybook stories in the `image-snapshots` suite so we can have good coverage for those going forward.

**Comment by ElliotTheHuman** [comment]
> Sorry, lost my own notes, changes look good but I think it'd be worthwhile to include the Storybook stories in the `image-snapshots` suite so we can have good coverage for those going forward.

Wasn't sure if we wanted image snapshots or not for these guys, but no complaints on my end towards adding them in! Resolved in 879f782!

**Comment by ElliotTheHuman** [comment]
Note: Went ahead and just added the docs to this PR (had a separate PR for it but figured it's small enough to sneak in with this guy.

**Review by lukelooker — APPROVED** [review]
LGTM! :)

**Pull request merged**
