### PR TITLE
update width from InputText

### PR DESCRIPTION
**Pull request by laraharrow**
### :sparkles: Changes

- update width on inputText

### :white_check_mark: Requirements

- [x] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] PR is ideally < 400LOC

### CODE REVIEW

**Comment by lukelooker** [comment]
@laraharrow Can you update PR description to remove stock text and add screenshot(s)?

**Comment by laraharrow** [comment]
@lukelooker ok I think it's good now!

**Comment by lukelooker** [comment]
So the goal is to get all `Field` components (not `FieldInline` however to fully-fill the container they are within: 

image

I added a commit of my work to get this screenshot to this branch.

**Comment by lukelooker** [comment]
@jhardy Can you check out this branch and tell me if this accomplishes what you were looking for?

**Comment by laraharrow** [comment]
I guess I missed the point here. Let me know if something else needs to be done here or if its ready after your work @lukelooker

**Comment by lukelooker** [comment]
Ok - poking around I found one more weirdness: 

image

InputText's with an icon show correctly whereas those without end up with a default width. Fix was pretty straightforward so I've added a commit to address that.

**Pull request merged**
